version: '3.8'

services:

  web:
    build: 
      context: ./YetAnotherDisk
      dockerfile: Dockerfile
    restart: always
    command: gunicorn YetAnotherDisk.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:14.4-alpine
    container_name: backendschool2022restapi_db_1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: